# Generated by Django 6.0.5 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderprofile",
            name="profile_photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="cover_photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
