# Generated by Django 6.0.5 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_profile_cover_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderprofile",
            name="profile_photo_file",
            field=models.FileField(blank=True, upload_to="profiles/avatars/"),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="cover_photo_file",
            field=models.FileField(blank=True, upload_to="profiles/covers/"),
        ),
    ]

